client_config_backend: settings
client_config:
  client_id: 321226991429-n37d3ebp4al3darlhl1ri6gp8bbm5t77.apps.googleusercontent.com
  client_secret: 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
save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json
get_refresh_token: True
oauth_scope:
  - https://www.googleapis.com/auth/drive.file
