jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Check out repository code
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'

        - name: Create settings.yaml
          run: |
            echo "client_config_backend: settings" > settings.yaml
            echo "client_config:" >> settings.yaml
            echo "  client_id: ${{ secrets.GOOGLE_CLIENT_ID }}" >> settings.yaml
            echo "  client_secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}" >> settings.yaml
            echo "save_credentials: True" >> settings.yaml
            echo "save_credentials_backend: file" >> settings.yaml
            echo "save_credentials_file: credentials.json" >> settings.yaml
            echo "get_refresh_token: True" >> settings.yaml
            echo "oauth_scope:" >> settings.yaml
            echo "  - https://www.googleapis.com/auth/drive" >> settings.yaml

        - name: Run the Python script
           run: drive.py
  